## python中异常处理主要有try和断言两种assert

#### try异常
```python
try:
  获取异常的代码块
except 异常名称 as 异常数据:
  print(异常数据)


raise 如果不抓取异常，主动抛出异常
```
except可以不捕获任何异常，执行异常后的代码
except(Exception1[, Exception2[,...ExceptionN]]]):可以捕获多种异常
try-finally 语句无论是否发生异常都将执行finally的代码

#### 断言(assert)
assert一般用法：

assert condition

如果condition为false，就raise一个AssertionError出来。逻辑上等同于：
```python
if not condition:
    raise AssertionError()
```
另一种使用方法：
assert condition，expression

如果condition为false，就raise一个描述为 expression 的AssertionError出来。逻辑上等同于：
```python
if not condition:
        raise AssertionError(expression)
```


#### 断言跟异常的区别：

断言是用来检查非法情况而不是错误情况的，用来帮开发者快速定位问题的位置。
异常处理用于对程序发生异常情况的处理，增强程序的健壮性和容错性。

对一个函数而言，一般情况下，断言用于检查函数输入的合法性，要求输入满足一定的条件才能继续执行;
在函数执行过程中出现的异常情况使用异常来捕获
